### ISSUE TITLE
Install error with windows

### ISSUE THREAD

**Issue by andresramos3** [AprilRobotics/apriltag#194]
having some issues installing the package in python - pycharm when I go to install the package it keeps giving me errors. I have tried to upgrade pip, install cmake, unistall and reinstall python and pycharm, tried installing directly from the terminal as in pip install apriltag. All attempts have not been successful. If anyone can help it would be great , I will attach the error code that it gave me. 

Collecting apriltag
  Using cached apriltag-0.0.16.tar.gz (201 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for apriltag, since package 'wheel' is not installed.
Installing collected packages: apriltag
    Running setup.py install for apriltag: started
    Running setup.py install for apriltag: finished with status 'error'

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\aramo\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\aramo\\AppData\\Local\\Temp\\pip-install-vwuemyjv\\apriltag_fe5beea884f847d0b9d836b0714ed702\\setup.py'"'"'; __file__='"'"'C:\\Users\\aramo\\AppData\\Local\\Temp\\pip-install-vwuemyjv\\apriltag_fe5beea884f847d0b9d836b0714ed702\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\aramo\AppData\Local\Temp\pip-record-jixjx7q0\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\aramo\AppData\Local\Programs\Python\Python310\Include\apriltag'
         cwd: C:\Users\aramo\AppData\Local\Temp\pip-install-vwuemyjv\apriltag_fe5beea884f847d0b9d836b0714ed702\
    Complete output (65 lines):
    running install
    C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    copying python\apriltag.py -> build\lib.win-amd64-3.10
    warning: build_py: byte-compiling is disabled, skipping.
   
    running build_ext
    C:\Users\aramo\AppData\Local\Temp\pip-install-vwuemyjv\apriltag_fe5beea884f847d0b9d836b0714ed702\setup.py:30: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      cmake_version = LooseVersion(re.search(r'version\s*([\d.]+)', out.decode()).group(1))
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:1 (project):
      Generator
   
        NMake Makefiles
   
      does not support platform specification, but platform
   
        x64
   
      was specified.
   
   
    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/aramo/AppData/Local/Temp/pip-install-vwuemyjv/apriltag_fe5beea884f847d0b9d836b0714ed702/build/temp.win-amd64-3.10/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\aramo\AppData\Local\Temp\pip-install-vwuemyjv\apriltag_fe5beea884f847d0b9d836b0714ed702\setup.py", line 62, in <module>
        setup(
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
        return run_commands(dist)
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
        dist.run_commands()
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 68, in run
        return orig.install.run(self)
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\install.py", line 664, in run
        self.run_command('build')
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\aramo\AppData\Local\Temp\pip-install-vwuemyjv\apriltag_fe5beea884f847d0b9d836b0714ed702\setup.py", line 35, in run
        self.build_extension(ext)
      File "C:\Users\aramo\AppData\Local\Temp\pip-install-vwuemyjv\apriltag_fe5beea884f847d0b9d836b0714ed702\setup.py", line 59, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "C:\Users\aramo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\aramo\\AppData\\Local\\Temp\\pip-install-vwuemyjv\\apriltag_fe5beea884f847d0b9d836b0714ed702', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\aramo\\AppData\\Local\\Temp\\pip-install-vwuemyjv\\apriltag_fe5beea884f847d0b9d836b0714ed702\\build\\lib.win-amd64-3.10', '-DPYTHON_EXECUTABLE=C:\\Users\\aramo\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\aramo\\AppData\\Local\\Temp\\pip-install-vwuemyjv\\apriltag_fe5beea884f847d0b9d836b0714ed702\\build\\lib.win-amd64-3.10', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\aramo\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\aramo\\AppData\\Local\\Temp\\pip-install-vwuemyjv\\apriltag_fe5beea884f847d0b9d836b0714ed702\\setup.py'"'"'; __file__='"'"'C:\\Users\\aramo\\AppData\\Local\\Temp\\pip-install-vwuemyjv\\apriltag_fe5beea884f847d0b9d836b0714ed702\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\aramo\AppData\Local\Temp\pip-record-jixjx7q0\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\aramo\AppData\Local\Programs\Python\Python310\Include\apriltag' Check the logs for full command output.

**Comment by christian-rauch** [comment]
The [apriltag pip package](https://pypi.org/project/apriltag/) is unrelated to this repo. Please report those pip issues to https://github.com/swatbotics/apriltag.
